return {
  Diagnostics = {
    Error = " ",
    Warn = " ",
    Info = " ",
    Hint = " ",
  },
  Git = {
    Added = " ",
    Modified = " ",
    Removed = " ",
  },
  lazy = {
    cmd = "⌘",
    config = "🛠️",
    event = "📅",
    ft = "📁",
    init = "⚙️",
    keys = "⌨️",
    lazy = "💤",
    loaded = "✅",
    not_loaded = "⭕",
    plugin = "📦",
    runtime = "💻",
    require = "📥",
    source = "📜",
    start = "🚀",
    task = "📌",
    favorite = "⭐",
    debug = "🐛",
    import = "📤",
    list = { "●", "➜", "★", "‒" },
  },
  lspkind = {
    Text          = "📜",
    Method        = "🗡️",
    Function      = "⚡",
    Constructor   = "🔨",
    Field         = "🔮",
    Variable      = "🌀",
    Class         = "🛡️",
    Interface     = "🔀",
    Module        = "📦",
    Property      = "💎",
    Unit          = "⏳",
    Value         = "🪙",
    Enum          = "🧬",
    Keyword       = "🔑",
    Snippet       = "📜",
    Color         = "🎨",
    File          = "📄",
    Reference     = "🔗",
    Folder        = "📁",
    EnumMember    = "🔹",
    Constant      = "🗿",
    Struct        = "🏰",
    Event         = "💥",
    Operator      = "⚔️",
    TypeParameter = "🎯",
    Copilot       = "🤖",
  },

  File = " ",
  Folder = " ",
}
